package org.walkwithgod.audit;

public enum AuditAction {
    // Users
    USER_CREATED,
    USER_UPDATED,
    USER_SUSPENDED,
    USER_REACTIVATED,
    ROLE_CHANGED,

    // Mentor workflow
    MENTOR_APPLICATION_SUBMITTED,
    MENTOR_APPLICATION_APPROVED,
    MENTOR_APPLICATION_REJECTED,
    MENTOR_REQUEST_SENT,
    MENTOR_REQUEST_ACCEPTED,
    MENTOR_REQUEST_DECLINED,

    // Community
    POST_CREATED,
    POST_DELETED,
    POST_REPORTED,
    COMMENT_DELETED,

    // Devotions
    DEVOTION_PUBLISHED,
    DEVOTION_DELETED,

    // Trivia
    TRIVIA_CREATED,
    TRIVIA_DELETED,

    //REPORTING
    REPORT_EXPORTED,

    //SETTING
    SETTING_UPDATED,

    //CALL
    CALL_COMPLETED,
    CALL_MISSED,

    // Auth
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ACCOUNT_LOCKED
}